name: movie_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_iconly: ^1.0.2
  material_floating_search_bar: ^0.3.7
  percent_indicator: ^4.2.2
  share_plus: ^4.2.0
  http: ^0.13.5
  path_provider: ^2.0.11
  flutter_rating_bar: ^4.0.1
  iconly: ^1.0.1
  intl_phone_field: ^3.1.0
  searchfield: ^0.7.0
  font_awesome_flutter: ^10.1.0
  flutter_vector_icons: ^1.0.0
  provider: ^6.0.3
  flutter_credit_card: ^3.0.3
  iconsax: ^0.0.8
  material_design_icons_flutter: ^5.0.6996
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  pinput: ^2.2.12
  flutter_svg: ^1.1.4
  flutter_spinkit: ^5.1.0
  email_validator: ^2.1.17
  form_validator: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/